---
  - name: Install and configure tomcat
    hosts: servers
    gather_facts: false
    become: yes
    vars:
        env_type: "{{ env }}"
    tasks:
      - name: updating repos
        apt:
          name: "*"
          state: latest

      - name: check if tomcat exist
        stat: path=/tmp/apache-tomcat-9.0.56
        register: tomcat

      - name: check if tomcat instance exist
        stat: path=/usr/share/tomcat9
        register: tomcat9
        
      - name: download required tomcat
        get_url:
          url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
          dest: /tmp
        when: tomcat.stat.isdir is not defined

      - name: extracting downloaded tomcat
        ansible.builtin.unarchive:
          src: /tmp/apache-tomcat-9.0.56.tar.gz
          dest: /tmp
          remote_src: yes
        when: tomcat.stat.isdir is not defined
        
      - name: deployment of tomcat
        command: mv /tmp/apache-tomcat-9.0.56 /usr/share/tomcat9
        when: tomcat9.stat.isdir is not defined
        
      - name: open tomcat ports in firewall
        command: firewall-cmd --permanent --zone=public --add-port=8080/tcp
        when: tomcat9.stat.isdir is not defined 
        
      - name: reload firewall
        command: firewall-cmd --reload
        when: tomcat9.stat.isdir is not defined
        
      - name: install tomcat as a service > download tomcat9.service
        get_url: 
          url: https://raw.githubusercontent.com/arthking17/DevOps_Technical_Test/main/tomcat9.service
          dest: /tmp/tomcat9.service

      - name: install tomcat as a service > add tomcat9.service
        command: cp /tmp/tomcat9.service /etc/systemd/system/tomcat9.service

      - name: install tomcat as a service > edit rights
        command: chown 700 /etc/systemd/system/tomcat9.service

      - name: install tomcat as a service > reload daemon
        command: systemctl daemon-reload

      - name: install tomcat as a service > enable tomcat9
        command: systemctl enable tomcat9.service

      - name: install tomcat as a service > create tomcat log dir
        command: mkdir -p /var/log/tomcat9

      - name: install tomcat as a service > create tomcat log file
        command: touch /var/log/tomcat9/catalina.out

      - name: launching instance tomcat
        command: nohup /usr/share/tomcat9/bin/catalina.sh start
        environment:
          CATALINA_HOME: /usr/share/tomcat9
          CATALINA_PID: /usr/share/tomcat9/logs/tomcat.pid
          CATALINA_OPTS: -Xmx256m
          CATALINA_OUT: /var/log/tomcat9/catalina.out
        when: env_type == "DEV"

      - name: launching instance tomcat
        command: nohup /usr/share/tomcat9/bin/catalina.sh start
        environment:
          CATALINA_HOME: /usr/share/tomcat9
          CATALINA_PID: /usr/share/tomcat9/logs/tomcat.pid
          CATALINA_OPTS: -Xmx512m
          CATALINA_OUT: /var/log/tomcat9/catalina.out
        when: env_type == "PROD"
        
      - name: download war file
        get_url: 
          url: https://github.com/arthking17/DevOps_Technical_Test/raw/main/sample.war
          dest: /tmp/sample-1.0.war
          
      - name: deploy war file on tomcat
        command: mv /tmp/sample-1.0.war /usr/share/tomcat9/webapps/sample.war
          
      - name: waiting launching of instance
        wait_for: port=8080
