---
  - name: Install and configure tomcat
    hosts: 
    gather_facts: false
    become: yes
    tasks:
      - name: updating repos
        yum:
          name: "*"
          state: latest
      - name: Installing required java
        yum:
          name: java-1.8.0-openjdk
          state: present
      - name: Setting default java
        alternatives:
          name: java
          link: /usr/bin/java
          path: /usr/lib/jvm/jre-1.8.0-openjdk/bin/java
      - name: download required tomcat
        get_url:
          url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.tar.gz
          dest: /usr/local
      - name: extracting downloaded tomcat
        unarchieve:
          src: "/usr/local/apache-tomacat-9.0.55.tar.gz"
          dest: /usr/local