- name: Test si une instance existe
    stat: path=/PROD/mywebapp/bin/catalina.sh
    register: p

- name: Arrêt de l'instance
  command: /PROD/mywebapp/bin/catalina.sh stop
  when: p.stat.isreg is defined and p.stat.isreg == true

- name: Suppression de l'instance
  command: rm -rf /PROD/mywebapp removes=/PROD/mywebapp

- name: Téléchargement de Tomcat
  get_url:
    url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.56/bin/apache-tomcat-7.0.56.tar.gz
    dest=/tmp/apache-tomcat-7.0.56.tar.gz

- name: Extraction de Tomcat
  command: chdir=/tmp tar xvf /tmp/apache-tomcat-7.0.56.tar.gz creates=/tmp/apache-tomcat-7.0.56

- name: Déploiement de Tomcat
  command: cp -r /tmp/apache-tomcat-7.0.56 /PROD/mywebapp creates=/PROD/mywebapp

- name: Téléchargement du WAR
  get_url:
    url=http://.../mywebapp-1.0.war
    dest=/tmp/mywebapp-1.0.war

- name: Copie de la webapp dans l'instance
  command: mv /tmp/mywebapp-1.0.war /PROD/mywebapp/webapps/mywebapp.war

- name: Démarrage de l'instance
  command: nohup /PROD/mywebapp/bin/catalina.sh start
  environment:
    CATALINA_HOME: /PROD/mywebapp
    CATALINA_PID: /PROD/mywebapp/logs/tomcat.pid

- name: Attente du démarrage de l'instance
  wait_for: port=8080